from database import Base
import sqlalchemy as sa
from sqlalchemy.orm import Mapped
from sqlalchemy.orm import mapped_column
from sqlalchemy_utils import EmailType, Timestamp
from utils.constants import UserRoles

class User(Base, Timestamp):
    __tablename__ = "users"

    id: Mapped[int] = mapped_column(primary_key=True)
    email: Mapped[str] = mapped_column(EmailType, unique=True)
    password: Mapped[str | None] = mapped_column(sa.String(255))
    active: Mapped[bool] = mapped_column(default=True, nullable=False)
    role: Mapped[str] = mapped_column(
        # ChoiceType from sqlalchemy_utils not used as migration adds extra length argument when autogenerated
        # So fix in migration file or use sqlalchemy default approach
        sa.Enum(
            UserRoles,
            native_enum=False,  # store as VARCHAR + CHECK instead of DB native enum
            create_constraint=True,
            length=30,
            values_callable=lambda enum: [e.value for e in enum],
        ),
        default=UserRoles.USER.value,
        nullable=False,
    )
